[package]
name = "chasing-lines"
version = "0.1.0"
authors = ["Matyas Komaromi fr0nt13r789@gmail.com"]
description = "Some cute lines, chasing one another"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
